### ISSUE TITLE
Example for use in class library

### ISSUE THREAD

**Issue by ColossusFX** [Marfusios/websocket-client#1]
Hi, 
Could you show a short example for using this properly in a client library?
I would like to add more exchanges.

I have it working in console app, but when when using in library I get errors and can’t run (pub key natural error)

Thanks if you can.

**Comment by Marfusios** [comment]
Hello, 

could you please provide some working solution? So I can test it and see errors. 

One example is Bitfinex library: 
[BitfinexWebsocketCommunicator](https://github.com/Marfusios/bitfinex-client-websocket/blob/master/src/Bitfinex.Client.Websocket/Websockets/BitfinexWebsocketCommunicator.cs) - only inherited from `WebsocketClient` and then there is 
[BitfinexWebsocketClient](https://github.com/Marfusios/bitfinex-client-websocket/blob/master/src/Bitfinex.Client.Websocket/Client/BitfinexWebsocketClient.cs#L41) which subscribes to `MessageReceived` stream (don't forget to unsubscribe via Dispose() to avoid memory leaks) and parse raw string messages into C# objects.

**Comment by ColossusFX** [comment]
Hi below is working coinbase console app
[(https://gist.github.com/ColossusFX/f83ddd03f53a0bf941e2d837e86e5ecf)]

But when i try to use same in class library, im getting errors (its probably somehting i'm doing)

```
public async Task Connect()
{
// websocket client code here
}
```

Call it in console app with 
```
 var client = new CoinbasePro.Client.Websocket.Client.CoinbaseProClient();
client.Connect().Wait();
```

Error

> System.IO.FileNotFoundException: 'Could not load file or assembly 'Serilog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'. The system cannot find the file specified.'

**Comment by ColossusFX** [comment]
Thanks for any help

**Comment by Marfusios** [comment]
The issue is with missing Serilog dependency. 
In case of [.NET Core](https://github.com/Marfusios/websocket-client/blob/master/test_integration/Websocket.Client.Sample/Websocket.Client.Sample.csproj#L9) you need to reference it only inside the library. 
In case of [full .NET framework](https://github.com/Marfusios/websocket-client/blob/master/test_integration/Websocket.Client.Sample.NetFramework/Websocket.Client.Sample.NetFramework.csproj#L38), you need to reference it inside the library and also in the client (console app, web app). 

I've also switched all my libraries into logging abstraction [LibLog](https://github.com/damianh/LibLog), it is better because it doesn't force clients to use one single implementation of logging (for example Serilog, NLog, etc), they can choose. 
[Reference example](https://github.com/Marfusios/websocket-client/blob/master/src/Websocket.Client/Websocket.Client.csproj#L25) and [usage example](https://github.com/Marfusios/websocket-client/blob/master/src/Websocket.Client/WebsocketClient.cs#L18). 
I recommend you doing the same with your library.
