### ISSUE TITLE
Support reconnection only when connection is closed

### ISSUE THREAD

**Issue by sahb1239** [Marfusios/websocket-client#24]
Hello,

Would it be possible for you to support only reconnection the client when the actual connection is closed?

With other words LastChance should be configurable to only reconnect if `_client.State != WebSocketState.Open`.

Sincerely,
Søren

**Comment by Marfusios** [comment]
Hello @sahb1239 , 

the main reason behind reconnection was exactly the opposite. 
Because native ClientWebsocket has some very large timeout, so when network corruption happens, the `State` property stays `WebSocketState.Open`. From my tests, it was around 20-30 seconds, which could be critical in the case of automated trading strategies.  

What is your use-case and context?
Also, you can leave  `IsReconnectionEnabled = true`  and set `ReconnectTimeoutMs = int.MaxValue`, it should behave as you described, it will wait for cancellation of the listening thread which performs reconnection.

**Comment by Marfusios** [comment]
@sahb1239  there is a new way to disable last chance reconnection, implemented in [version 4.0](https://github.com/Marfusios/websocket-client/releases/tag/v4.0). 
Let me know if it is fine for you.

**Comment by Erutan409** [comment]
For anyone else coming across this, wanting to understand how the ping/pong functionality works (automatically) with this library, [see this](https://github.com/dotnet/runtime/blob/dc9c9d5f9e23ff6aa0b99af8f6c410a0558fadaf/src/libraries/System.Net.WebSockets/src/System/Net/WebSockets/ManagedWebSocket.cs#L777-L781) for how it's implemented in the native library.

I needed to disable the automatic reconnection in this library while refactoring the official Pusher C# library to use the modern functionality. This then stopped renewing my connecting with my Pusher server.
