### ISSUE TITLE
Help with Socket.IO websocket connection

### ISSUE THREAD

**Issue by simplextech** [Marfusios/websocket-client#4]
For the life of me and others I can't get a functioning websocket connection to this service.  I'm hoping your client may work with some assistance?

https://ambientweather.docs.apiary.io/#reference/ambient-realtime-api

**Comment by Marfusios** [comment]
Hello, 

you need to get url address like `wss://xxx` in order to use this library. 
But in your case, there is only `https://api.ambientweather.net/?api=1&applicationKey=....` and it is based on framework socket.io, I've no idea how it works internally and where to get correct websocket url. 

Try luck with these library, seems relevant: https://github.com/IBM/socket-io

**Comment by Marfusios** [comment]
Here is an interesting code: https://github.com/IBM/socket-io/blob/master/ibm.socket-io.client/Impl/SocketMediator.cs#L221 
There is some wss url resolving via HTTP call, weird to me, but perhaps meaningful.

**Comment by simplextech** [comment]
This is the problem I and others are having.  I've even looked into finding a commercial library offering to find something and there is no current/maintained solution I can find for this that is functional for production use.

**Comment by Marfusios** [comment]
If you are willing to pay, contact me on my email. We can discuss some custom implementation for your issue.
