### ISSUE TITLE
Please update NuGet dependencies to newest

### ISSUE THREAD

**Issue by IvanGit** [Marfusios/websocket-client#41]
Hello,

I spend a lot of time investigating why web sockets didn't work properly in Release mode of my app.
The reason was in replacing System.Runtime.CompilerServices.Unsafe.dll by newest version used in other packages.

Regards,
IvanGit

**Comment by Marfusios** [comment]
Hello @IvanGit, 

what was the issue? 

The updating is quite tricky because I would like to support as broad range of clients as possible. 
So the library targets the lowest possible .NET standard - 2.0. 

Also, it doesn't reference any unnecessary stuff, only: 
![image](https://user-images.githubusercontent.com/3494837/74533272-7a2d4380-4f31-11ea-9d20-86653c5ff881.png)

`System.Runtime.CompilerServices.Unsafe` has to be a transitive dependency. 
Only `System.Reactive` is available to update, try the latest version [4.1.79](https://www.nuget.org/packages/Websocket.Client/4.1.79), I've updated it to 4.3.2. 
Hopefully, some other user is not stuck on version 4.0.0 for some reason.

**Comment by IvanGit** [comment]
> what was the issue?
I didn't receive messages in MessageReceived after client.Send. Before Send messages was received.

Yes, after updating System.Reactive and removing old System.Runtime.CompilerServices.Unsafe v4.0.4.1 and replacing with v4.0.6.0, the issue has been solved. Just FYI, if someone runs into a problem.
