### ISSUE TITLE
StackTrace of exceptions doesn't reach the log

### ISSUE THREAD

**Issue by drauch** [Marfusios/websocket-client#54]
Hi!

I'm using SlackConnector for my Slack-Bot to talk to Slack. It uses WebsocketClient internally to do the actual communication.

In your WebsocketClient class you log connection errors like so:

```
WebsocketClient.Logger.Error(websocketClient1.L("Exception while connecting. " + string.Format("Reconnecting canceled by user, exiting. Error: '{0}'", (object) ex.Message)));
```

As you can see, you omit the actual exception and just add the exception message to the log message. This prevents me from seeing stack traces in my logs, so I don't know which SlackConnector component actually faced the problem.

Is it possible to improve the situation and pass along the exception to all Logger.Error calls?

Best regards,
D.R.

**Comment by Marfusios** [comment]
Hello @drauch, 

good idea. 
I've removed that exception passing in some previous versions because it bloated default logs. 
But I see it would be a more standard way to provide that information and just configure logs not to show it. 
Feel free to provide PR. It will take me some time until I get to it.

**Comment by drauch** [comment]
Here is a PR. I've not found any tests for logging, so it was a very quick thing.

Best regards,
D.R.
